apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
   path('', views.view_cart, name='view_cart'),
   path('update_item/<int:item_id>/', views.update_item, name='update_item'),
   path('remove_item/<int:item_id>/', views.remove_item, name='remove_item'),
   path('checkout/', views.checkout, name='checkout'),
]

apps/cart_shop/urls.py
from django.urls import path
from .views import ViewCart, ViewWishlist, ViewCartBuy, ViewCartDel, ViewCartAdd, WishlistAdd, WishListDel

app_name = 'cart_shop'

urlpatterns = [
   path('', ViewCart.as_view(), name='cart'),
   path('wishlist/', ViewWishlist.as_view(), name='wishlist'),
   path('buy/<int:product_id>', ViewCartBuy.as_view(), name='buy'),
   path('del/<int:item_id>', ViewCartDel.as_view(), name='del_from_cart'),
   path('add/<int:product_id>', ViewCartAdd.as_view(), name='add_to_cart'),
   path('rise/<int:product_id>', WishlistAdd.as_view(), name='rise_wishlist'),
   path('remove/<int:product_id>', WishListDel.as_view(), name='remove_from_wish')

]

apps/checkout/urls.py
from django.urls import path
from .views import ViewCheckout

app_name = 'checkout'

urlpatterns = [
   path('', ViewCheckout.as_view(), name='checkout'),
]

apps/home/urls.py
from django.urls import path
from .views import IndexShopView, IndexAbout, IndexContact, IndexBlog

app_name = 'home'

urlpatterns = [
   path('', IndexShopView.as_view(), name='index'),
   path('', IndexAbout.as_view(), name='about'),
   path('', IndexContact.as_view(), name='contact'),
   path('', IndexBlog.as_view, name='blog')

]

apps/shop/urls.py
from django.urls import path
from .views import ViewShop, ViewProductSingle

app_name = 'shop'

urlpatterns = [
   path('', ViewShop.as_view(), name='shop'),
   path('', ViewProductSingle.as_view(), name='product-single'),
]

lab_1/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('other/', include('apps.common.urls')),
    path('other', include('apps.test_app.urls')),
    path('other', include('apps.login.urls')),
    path('other/cart/', include('apps.cart.urls')),
    path('', include('apps.home.urls')),
    path('cart/', include('apps.cart_shop.urls')),
    path('blog/', include('apps.blog.urls')),
    path('checkout/', include('apps.checkout.urls')),
    path('shop/', include('apps.shop.urls')),
    path('login/', include('apps.auth_shop.urls')),


]

apps/cart/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

# Create your models here.

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user}"


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(upload_to='static/products/', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        img = img.resize((100, 100), Image.ANTIALIAS)
        img.save(self.image.path)

    def __str__(self):
        return self.name


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.cart}_{self.product}"

apps/cart_shop/models.py
from django.db import models
from apps.cart.models import Cart

# Create your models here.


class Product(models.Model):
    name = models.CharField(max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount = models.IntegerField(null=True, blank=True)
    description = models.TextField()
    image = models.ImageField(upload_to='static/shop/images', null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class CartItemShop(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.cart}_{self.product}"


class WishList(models.Model):
   cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
   product = models.ForeignKey(Product, on_delete=models.CASCADE)
   quantity = models.IntegerField(default=1)
   created_at = models.DateTimeField(auto_now_add=True)
   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
       return f"{self.cart}_{self.product}"

apps/cart/views.py
from django.shortcuts import render, redirect
from .models import Cart, CartItem


# Create your views here.

def view_cart(request):
    cart_items = CartItem.objects.filter(cart__user=request.user)
    total_price = sum(item.product.price * item.quantity for item in cart_items)
    context = {'cart_items': cart_items, 'total_price': total_price}
    return render(request, 'cart/cart.html', context)


def update_item(request, item_id):
    item = CartItem.objects.get(id=item_id)
    item.quantity += int(request.GET.get('quantity'))
    item.save()
    return redirect('cart:view_cart')


def remove_item(request, item_id):
    CartItem.objects.filter(id=item_id).delete()
    return redirect('cart:view_cart')


def checkout(request):
    # code to handle checkout process
    return redirect('cart:view_cart')

apps/cart_shop/views.py
from django.shortcuts import get_object_or_404, redirect
from django.shortcuts import render
from django.views import View
from .models import CartItemShop, Cart, Product, WishList
from django.contrib.auth.models import User


class ViewCart(View):
    def get(self, request):
        cart_items = CartItemShop.objects.filter(cart__user=request.user)
        data = list(cart_items)
        total_price_no_discount = sum(item.product.price * item.quantity for item in data)
        total_discount = sum(item.product.price * item.product.discount * item.quantity for item in data if
                             item.product.discount is not None) / 100
        total_sum = total_price_no_discount - total_discount
        context = {'cart_items': data,
                   'total_price_no_discount': total_price_no_discount,
                   'total_discount': total_discount,
                   'total_sum': total_sum,
                   }
        return render(request, 'cart_shop/cart.html', context)


def save_product_in_cart(request, product_id):
    cart_items = CartItemShop.objects.filter(cart__user=request.user,
                                             product__id=product_id)
    if cart_items:
        cart_item = cart_items[0]
        cart_item.quantity += 1
    else:
        product = get_object_or_404(Product, id=product_id)
        cart_user = get_object_or_404(Cart, user=request.user)
        cart_item = CartItemShop(cart=cart_user, product=product)
    cart_item.save()


class ViewCartBuy(View):
    def get(self, request, product_id):
        save_product_in_cart(request, product_id)
        return redirect('cart_shop:cart')


class ViewCartDel(View):
    def get(self, request, item_id):
        cart_item = get_object_or_404(CartItemShop, id=item_id)
        cart_item.delete()
        return redirect('cart_shop:cart')


class ViewCartAdd(View):
    def get(self, request, product_id):
        save_product_in_cart(request, product_id)
        return redirect('home:index')


'''
class ViewWishlist(View):
    def get(self, request):
        data = Product.objects.all()
        context = {'data': data
                   }
        return render(request, 'cart_shop/wishlist.html', context)

       context = {'data': [{'name': 'Название овоща из context',
                            'price_before': 120.00,
                            'url': 'shop/images/product-1.jpg'}
                           ]
                  }
'''


class ViewWishlist(View):
    def get(self, request):
        if not request.user.is_authenticated:
            return render(request, 'cart_shop/404.html')
        cart_items = WishList.objects.filter(cart__user=request.user)
        data = list(cart_items)
        context = {'cart_items': data}
        return render(request, 'cart_shop/wishlist.html', context)


class WishlistAdd(View):
    def get(self, request, product_id):
        if not request.user.is_authenticated:
            return render(request, 'cart_shop/404.html')
        wish_items = WishList.objects.filter(cart__user=request.user,
                                             product__id=product_id)
        if not wish_items:
            product = get_object_or_404(Product, id=product_id)
            cart_user = get_object_or_404(Cart, user=request.user)
            wish_item = WishList(cart=cart_user, product=product)
            wish_item.save()
        wish_items = WishList.objects.filter(cart__user=request.user)
        data = list(wish_items)
        context = {'cart_items': data}
        return render(request, 'cart_shop/wishlist.html', context)



class WishListDel(View):
   def get(self, request, product_id):
       wish_item = get_object_or_404(WishList, id=product_id)
       wish_item.delete()
       return redirect('cart_shop:wishlist')
       

apps/cart_shop/templates/cart_shop/cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Vegefoods - Free Bootstrap 4 Template by Colorlib</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,500,600,700,800&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Amatic+SC:400,700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'shop/css/open-iconic-bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'shop/css/animate.css'%}">
    
    <link rel="stylesheet" href="{% static 'shop/css/owl.carousel.min.css'%}">
    <link rel="stylesheet" href="{% static 'shop/css/owl.theme.default.min.css'%}">
    <link rel="stylesheet" href="{% static 'shop/css/magnific-popup.css'%}">

    <link rel="stylesheet" href="{% static 'shop/css/aos.css'%}">

    <link rel="stylesheet" href="{% static 'shop/css/ionicons.min.css'%}">

    <link rel="stylesheet" href="{% static 'shop/css/bootstrap-datepicker.css'%}">
    <link rel="stylesheet" href="{% static 'shop/css/jquery.timepicker.css'%}">

    
    <link rel="stylesheet" href="{% static 'shop/css/flaticon.css'%}">
    <link rel="stylesheet" href="{% static 'shop/css/icomoon.css'%}">
    <link rel="stylesheet" href="{% static 'shop/css/style.css'%}">
  </head>
  <body class="goto-here">
		<div class="py-1 bg-primary">
    	<div class="container">
    		<div class="row no-gutters d-flex align-items-start align-items-center px-md-0">
	    		<div class="col-lg-12 d-block">
		    		<div class="row d-flex">
		    			<div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-phone2"></span></div>
						    <span class="text">+ 1235 2355 98</span>
					    </div>
					    <div class="col-md pr-4 d-flex topper align-items-center">
					    	<div class="icon mr-2 d-flex justify-content-center align-items-center"><span class="icon-paper-plane"></span></div>
						    <span class="text">youremail@email.com</span>
					    </div>
					    <div class="col-md-5 pr-4 d-flex topper align-items-center text-lg-right">
						    <span class="text">3-5 Business days delivery &amp; Free Returns</span>
					    </div>
				    </div>
			    </div>
		    </div>
		  </div>
    </div>
    <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
	    <div class="container">
	      <a class="navbar-brand" href="{% url 'home:index' %}">Vegefoods</a>
	      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav" aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
	        <span class="oi oi-menu"></span> Menu
	      </button>

	      <div class="collapse navbar-collapse" id="ftco-nav">
	        <ul class="navbar-nav ml-auto">
	          <li class="nav-item"><a href="{% url 'home:index' %}" class="nav-link">Home</a></li>
	          <li class="nav-item active dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="dropdown04" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Shop</a>
              <div class="dropdown-menu" aria-labelledby="dropdown04">
              	<a class="dropdown-item" href="{% url 'shop:shop' %}">Shop</a>
              	<a class="dropdown-item" href="{% url 'cart_shop:wishlist' %}">Wishlist</a>
                <a class="dropdown-item" href="{% url 'shop:product-single' %}">Single Product</a>
                <a class="dropdown-item" href="{% url 'cart_shop:cart' %}">Cart</a>
                <a class="dropdown-item" href="{% url 'checkout:checkout' %}">Checkout</a>
              </div>
            </li>
	          <li class="nav-item"><a href="{% url 'home:about' %}" class="nav-link">About</a></li>
	          <li class="nav-item"><a href="{% url 'home:blog' %}" class="nav-link">Blog</a></li>
	          <li class="nav-item"><a href="{% url 'home:contact' %}" class="nav-link">Contact</a></li>
	          <li class="nav-item cta cta-colored"><a href="{% url 'cart_shop:cart' %}" class="nav-link"><span class="icon-shopping_cart"></span>{{ cart_items|length}}</a></li>

	        </ul>
	      </div>
	    </div>
	  </nav>
    <!-- END nav -->

    <div class="hero-wrap hero-bread" style="background-image: url({% static 'shop/images/bg_1.jpg'%});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Cart</span></p>
            <h1 class="mb-0 bread">My Cart</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>&nbsp;</th>
						        <th>Product name</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>
							{% for item in cart_items %}
							<tr class="text-center">
							  <td class="product-remove"><a href="{% url 'cart_shop:del_from_cart' item.id %}"><span class="ion-ios-close"></span></a></td>

							  <td class="image-prod"><div class="img" style="background-image:url({{item.product.image.url}});"></div></td>

							  <td class="product-name">
								  <h3>{{item.product.name}}</h3>
								  <p>{{item.product.description}}</p>
							  </td>

							  <td class="price">${{item.product.price}}</td>

							  <td class="quantity">
								  <div class="input-group mb-3">
									  <input type="text" name="quantity" class="quantity form-control input-number" value={{item.quantity}} min="1" max="100">
								  </div>
							  </td>

							  <td class="total">${% widthratio item.product.price 1 item.quantity %}</td>
							</tr><!-- END TR-->
						{%endfor%}


						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
    		<div class="row justify-content-end">
    			<div class="col-lg-4 mt-5 cart-wrap ftco-animate">
    				<div class="cart-total mb-3">
  <h3>Cart Totals</h3>
  <p class="d-flex">
     <span>Subtotal</span>
     <span>${{total_price_no_discount}}</span>
  </p>
  <p class="d-flex">
     <span>Delivery</span>
     <span>$0.00</span>
  </p>
  <p class="d-flex">
     <span>Discount</span>
     <span>${{total_discount}}</span>
  </p>
  <hr>
  <p class="d-flex total-price">
     <span>Total</span>
     <span>${{total_sum}}</span>
  </p>
</div>

    				<p><a href="checkout.html" class="btn btn-primary py-3 px-4">Apply Coupon</a></p>
    			</div>

    		</div>
			</div>
		</section>

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
          	<h2 style="font-size: 22px;" class="mb-0">Subcribe to our Newsletter</h2>
          	<span>Get e-mail updates about our latest shops and special offers</span>
          </div>
          <div class="col-md-6 d-flex align-items-center">
            <form action="#" class="subscribe-form">
              <div class="form-group d-flex">
                <input type="text" class="form-control" placeholder="Enter email address">
                <input type="submit" value="Subscribe" class="submit px-3">
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>
    <footer class="ftco-footer ftco-section">
      <div class="container">
      	<div class="row">
      		<div class="mouse">
						<a href="#" class="mouse-icon">
							<div class="mouse-wheel"><span class="ion-ios-arrow-up"></span></div>
						</a>
					</div>
      	</div>
        <div class="row mb-5">
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Vegefoods</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia.</p>
              <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                <li class="ftco-animate"><a href="#"><span class="icon-twitter"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-facebook"></span></a></li>
                <li class="ftco-animate"><a href="#"><span class="icon-instagram"></span></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4 ml-md-5">
              <h2 class="ftco-heading-2">Menu</h2>
              <ul class="list-unstyled">
                <li><a href="#" class="py-2 d-block">Shop</a></li>
                <li><a href="#" class="py-2 d-block">About</a></li>
                <li><a href="#" class="py-2 d-block">Journal</a></li>
                <li><a href="#" class="py-2 d-block">Contact Us</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
             <div class="ftco-footer-widget mb-4">
              <h2 class="ftco-heading-2">Help</h2>
              <div class="d-flex">
	              <ul class="list-unstyled mr-l-5 pr-l-3 mr-4">
	                <li><a href="#" class="py-2 d-block">Shipping Information</a></li>
	                <li><a href="#" class="py-2 d-block">Returns &amp; Exchange</a></li>
	                <li><a href="#" class="py-2 d-block">Terms &amp; Conditions</a></li>
	                <li><a href="#" class="py-2 d-block">Privacy Policy</a></li>
	              </ul>
	              <ul class="list-unstyled">
	                <li><a href="#" class="py-2 d-block">FAQs</a></li>
	                <li><a href="#" class="py-2 d-block">Contact</a></li>
	              </ul>
	            </div>
            </div>
          </div>
          <div class="col-md">
            <div class="ftco-footer-widget mb-4">
            	<h2 class="ftco-heading-2">Have a Questions?</h2>
            	<div class="block-23 mb-3">
	              <ul>
	                <li><span class="icon icon-map-marker"></span><span class="text">203 Fake St. Mountain View, San Francisco, California, USA</span></li>
	                <li><a href="#"><span class="icon icon-phone"></span><span class="text">+2 392 3929 210</span></a></li>
	                <li><a href="#"><span class="icon icon-envelope"></span><span class="text">info@yourdomain.com</span></a></li>
	              </ul>
	            </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-12 text-center">

            <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
						  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</p>
          </div>
        </div>
      </div>
    </footer>
    
  

  <!-- loader -->
  <div id="ftco-loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#F96D00"/></svg></div>


  <script src="{% static 'shop/js/jquery.min.js'%}"></script>
  <script src="{% static 'shop/js/jquery-migrate-3.0.1.min.js'%}"></script>
  <script src="{% static 'shop/js/popper.min.js'%}'%}"></script>
  <script src="{% static 'shop/js/jquery.easing.1.3.js'%}"></script>
  <script src="{% static 'shop/js/jquery.waypoints.min.js'%}"></script>
  <script src="{% static 'shop/js/jquery.stellar.min.js'%}"></script>
  <script src="{% static 'shop/js/owl.carousel.min.js'%}"></script>
  <script src="{% static 'shop/js/jquery.magnific-popup.min.js'%}"></script>
  <script src="{% static 'shop/js/aos.js'%}"></script>
  <script src="{% static 'shop/js/jquery.animateNumber.min.js'%}"></script>
  <script src="{% static 'shop/js/bootstrap-datepicker.js'%}"></script>
  <script src="{% static 'shop/js/scrollax.min.js'%}"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
  <script src="{% static 'shop/js/google-map.js'%}"></script>
  <script src="{% static 'shop/js/main.js'%}"></script>

  <script>
		$(document).ready(function(){

		var quantitiy=0;
		   $('.quantity-right-plus').click(function(e){
		        
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		            
		            $('#quantity').val(quantity + 1);

		          
		            // Increment
		        
		    });

		     $('.quantity-left-minus').click(function(e){
		        // Stop acting like a button
		        e.preventDefault();
		        // Get the field name
		        var quantity = parseInt($('#quantity').val());
		        
		        // If is not undefined
		      
		            // Increment
		            if(quantity>0){
		            $('#quantity').val(quantity - 1);
		            }
		    });
		    
		});
	</script>
    
  </body>
</html>

apps/cart_shop/templates/cart_shop/wishlist.html
{% extends 'home/base.html' %}
{% load static %}

{% block content %}
    <div class="hero-wrap hero-bread" style="background-image: url({% static 'shop/images/bg_1.jpg'%});">
      <div class="container">
        <div class="row no-gutters slider-text align-items-center justify-content-center">
          <div class="col-md-9 ftco-animate text-center">
          	<p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Wishlist</span></p>
            <h1 class="mb-0 bread">My Wishlist</h1>
          </div>
        </div>
      </div>
    </div>

    <section class="ftco-section ftco-cart">
			<div class="container">
				<div class="row">
    			<div class="col-md-12 ftco-animate">
    				<div class="cart-list">
	    				<table class="table">
						    <thead class="thead-primary">
						      <tr class="text-center">
						        <th>&nbsp;</th>
						        <th>Product List</th>
						        <th>&nbsp;</th>
						        <th>Price</th>
						        <th>Quantity</th>
						        <th>Total</th>
						      </tr>
						    </thead>
						    <tbody>


								{% for item in cart_items %}

						      <tr class="text-center">
						        <td class="product-remove"><a href="{% url 'cart_shop:remove_from_wish' item.id %}"><span class="ion-ios-close"></span></a></td>
						        
						        <td class="image-prod"><div class="img" style="background-image:url({{item.product.image.url}});"></div></td>
						        
						        <td class="product-name">
						        	<h3>{{item.product.name}}</h3>
						        	<p>{{item.product.description}}</p>
						        </td>
						        
						        <td class="price">{{item.product.price}}</td>
						        
						        <td class="quantity">
						        	<div class="input-group mb-3">
					             	<input type="text" name="quantity" class="quantity form-control input-number" value={{item.quantity}} min="1" max="100">
					          	</div>
					          </td>
						        
						        <td class="total">${% widthratio item.product.price 1 item.quantity %}</td>
						      </tr>
								<!-- END TR-->

								{% endfor %}


						    </tbody>
						  </table>
					  </div>
    			</div>
    		</div>
			</div>
		</section>

		<section class="ftco-section ftco-no-pt ftco-no-pb py-5 bg-light">
      <div class="container py-4">
        <div class="row d-flex justify-content-center py-5">
          <div class="col-md-6">
{% endblock %}